In [18]:
from sklearn import datasets
import numpy as np

In [19]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [32]:
def LogisticGD(x, y, w, b=0, learning_rate=0.001, epoch=10000):
    for epochs in range(epoch):
        z = x.dot(w) + b
        pred = sigmoid(z)
        err = -np.log(pred) * y - np.log(1 - pred) * (1 - y)
        err = err.mean()
    
        dw = (pred - y).dot(x)
        db = (pred - y).mean()
        w -= dw * learning_rate
        b -= db * learning_rate
        if epochs % 1000 == 0:
            print(err)
    return w, b


In [33]:
cancer = datasets.load_breast_cancer()

In [34]:
cancer['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [35]:
x = cancer.data

In [36]:
x = x / x.mean()
x

array([[2.90673662e-01, 1.67714987e-01, 1.98414262e+00, ...,
        4.28820400e-03, 7.43407181e-03, 1.92112832e-03],
       [3.32360046e-01, 2.87119009e-01, 2.14733350e+00, ...,
        3.00529745e-03, 4.44331612e-03, 1.43834182e-03],
       [3.18141434e-01, 3.43347155e-01, 2.10047671e+00, ...,
        3.92627570e-03, 5.83770951e-03, 1.41507500e-03],
       ...,
       [2.68214719e-01, 4.53702970e-01, 1.74985868e+00, ...,
        2.29113537e-03, 3.58373642e-03, 1.26351753e-03],
       [3.32844771e-01, 4.73899861e-01, 2.26366760e+00, ...,
        4.28174099e-03, 6.60357563e-03, 2.00353163e-03],
       [1.25382302e-01, 3.96505373e-01, 7.74268031e-01, ...,
        0.00000000e+00, 4.63882203e-03, 1.13732735e-03]])

In [37]:
x.shape[1]

30

In [38]:
y = cancer['target']

In [39]:
w = np.random.uniform(-1, 1, x.shape[1])
w

array([ 0.57381109, -0.79787878, -0.10232489,  0.21528742, -0.42316939,
       -0.57680121, -0.64448099, -0.64574874,  0.09136471, -0.99865017,
        0.82209171,  0.65134696,  0.00902343, -0.72792041,  0.53567535,
        0.59251392, -0.31934359, -0.70603515,  0.09126273,  0.43186034,
       -0.85598411, -0.87639271, -0.2799344 , -0.88448635,  0.22846534,
       -0.18496814, -0.75219744, -0.29530359, -0.23063012, -0.395073  ])

In [43]:
b = 0
learning_rate = 0.0001
epoch = 100

In [28]:
z = x.dot(w)+b
z

array([10.69784895,  6.43075077,  5.25124537,  3.05137502,  2.69722637,
        3.72023992,  6.4060365 ,  4.14445839,  3.38454447,  3.64479864,
        4.42915647,  6.11354917,  2.49322331,  1.66166244,  2.38807396,
        4.11799469,  5.5500016 ,  6.15456557, 11.90806968,  2.27753921,
        2.02905115,  1.19895846,  3.61990967, 12.56864663, 14.14279104,
        6.03288786,  3.79624938,  3.34638542,  6.79994972,  3.20744644,
        6.40768598,  5.83547862,  5.19001028,  7.12947088,  5.4841834 ,
        4.43463338,  2.81055685,  1.01468615,  0.2141169 ,  2.90174158,
        3.30153784,  2.69363908,  6.32772996,  4.7609935 ,  3.27581184,
        5.37018178,  1.32266793,  3.30280317,  2.25204851,  2.42588844,
        1.77763655,  1.72847609,  1.7638883 ,  3.07562086,  4.16399924,
        1.84942244, 10.41161629,  4.27355033,  1.7175754 ,  1.31846113,
        1.29449026,  1.52578683,  4.09165027,  1.33310838,  5.15021217,
        3.60172404,  1.70029481,  1.62418186,  1.68845303,  1.28

In [40]:
pred = sigmoid(z)
pred

array([0.99997741, 0.99839135, 0.99478634, 0.95484185, 0.93686278,
       0.97634496, 0.99835117, 0.98439535, 0.967218  , 0.97453855,
       0.98821597, 0.9977922 , 0.92366538, 0.84046104, 0.91591335,
       0.98398358, 0.9961276 , 0.99788074, 0.99999326, 0.90699968,
       0.88381368, 0.76833945, 0.97391363, 0.99999652, 0.99999928,
       0.99760718, 0.97803831, 0.96598627, 0.99888741, 0.96111354,
       0.99835388, 0.99708649, 0.99445893, 0.9991995 , 0.99586524,
       0.98827958, 0.94324364, 0.73393623, 0.55332565, 0.94793246,
       0.96448153, 0.93665026, 0.9982171 , 0.9915155 , 0.96358963,
       0.99536827, 0.78962524, 0.96452485, 0.90482709, 0.91878024,
       0.85540478, 0.84921739, 0.85369597, 0.95587585, 0.98469269,
       0.86405928, 0.99996992, 0.98625921, 0.84781627, 0.78892557,
       0.78490624, 0.82138904, 0.98356306, 0.79135433, 0.99423525,
       0.9734476 , 0.84557323, 0.83537105, 0.84402061, 0.78394243,
       0.99961655, 0.76188312, 0.99977877, 0.96301111, 0.91061

In [44]:
w, b = LogisticGD(x, y, w, b, learning_rate, epoch)

4.8793832081528725


In [45]:
import matplotlib.pypplot as plt

ModuleNotFoundError: No module named 'matplotlib.pypplot'